In [1]:
!git clone https://github.com/PhonePe/pulse.git

Cloning into 'pulse'...
Updating files:   8% (768/9029)
Updating files:   9% (813/9029)
Updating files:  10% (903/9029)
Updating files:  11% (994/9029)
Updating files:  12% (1084/9029)
Updating files:  13% (1174/9029)
Updating files:  14% (1265/9029)
Updating files:  15% (1355/9029)
Updating files:  16% (1445/9029)
Updating files:  17% (1535/9029)
Updating files:  18% (1626/9029)
Updating files:  18% (1654/9029)
Updating files:  19% (1716/9029)
Updating files:  20% (1806/9029)
Updating files:  21% (1897/9029)
Updating files:  22% (1987/9029)
Updating files:  23% (2077/9029)
Updating files:  24% (2167/9029)
Updating files:  25% (2258/9029)
Updating files:  26% (2348/9029)
Updating files:  27% (2438/9029)
Updating files:  27% (2485/9029)
Updating files:  28% (2529/9029)
Updating files:  29% (2619/9029)
Updating files:  30% (2709/9029)
Updating files:  31% (2799/9029)
Updating files:  32% (2890/9029)
Updating files:  33% (2980/9029)
Updating files:  33% (3002/9029)
Updating files:  34% (3070/9029)
Updating files:  35% (3161/9029)
Updating files:  36% (3251/9029)
Updating files:  37% (3341/9029)
Updating files:  38% (3432/9029)
Updating files:  38% (3433/9029)
Updating files:  39% (3522/9029)
Updating files:  40% (3612/9029)
Updating files:  41% (3702/9029)
Updating files:  42% (3793/9029)
Updating files:  43% (3883/9029)
Updating files:  44% (3973/9029)
Updating files:  45% (4064/9029)
Updating files:  46% (4154/9029)
Updating files:  46% (4227/9029)
Updating files:  47% (4244/9029)
Updating files:  48% (4334/9029)
Updating files:  49% (4425/9029)
Updating files:  50% (4515/9029)
Updating files:  51% (4605/9029)
Updating files:  52% (4696/9029)
Updating files:  53% (4786/9029)
Updating files:  54% (4876/9029)
Updating files:  55% (4966/9029)
Updating files:  56% (5057/9029)
Updating files:  56% (5135/9029)
Updating files:  57% (5147/9029)
Updating files:  58% (5237/9029)
Updating files:  59% (5328/9029)
Updating files:  60% (5418/9029)
Updating files:  61% (5508/9029)
Updating files:  62% (5598/9029)
Updating files:  63% (5689/9029)
Updating files:  64% (5779/9029)
Updating files:  64% (5787/9029)
Updating files:  65% (5869/9029)
Updating files:  66% (5960/9029)
Updating files:  67% (6050/9029)
Updating files:  68% (6140/9029)
Updating files:  69% (6231/9029)
Updating files:  70% (6321/9029)
Updating files:  71% (6411/9029)
Updating files:  72% (6501/9029)
Updating files:  73% (6592/9029)
Updating files:  73% (6649/9029)
Updating files:  74% (6682/9029)
Updating files:  75% (6772/9029)
Updating files:  76% (6863/9029)
Updating files:  77% (6953/9029)
Updating files:  78% (7043/9029)
Updating files:  79% (7133/9029)
Updating files:  80% (7224/9029)
Updating files:  81% (7314/9029)
Updating files:  82% (7404/9029)
Updating files:  83% (7495/9029)
Updating files:  83% (7503/9029)
Updating files:  84% (7585/9029)
Updating files:  85% (7675/9029)
Updating files:  86% (7765/9029)
Updating files:  87% (7856/9029)
Updating files:  88% (7946/9029)
Updating files:  89% (8036/9029)
Updating files:  90% (8127/9029)
Updating files:  91% (8217/9029)
Updating files:  92% (8307/9029)
Updating files:  92% (8377/9029)
Updating files:  93% (8397/9029)
Updating files:  94% (8488/9029)
Updating files:  95% (8578/9029)
Updating files:  96% (8668/9029)
Updating files:  97% (8759/9029)
Updating files:  98% (8849/9029)
Updating files:  99% (8939/9029)
Updating files: 100% (9029/9029)
Updating files: 100% (9029/9029), done.

In [3]:
!pip install pandas

Collecting pandas
  Using cached pandas-2.3.1-cp313-cp313-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.3.2-cp313-cp313-win_amd64.whl.metadata (60 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\admin\documents\phonepay_project\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Using cached pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Using cached tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\admin\documents\phonepay_project\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-2.3.1-cp313-cp313-win_amd64.whl (11.0 MB)
Downloading numpy-2.3.2-cp313-cp313-win_amd64.whl (12.8 MB)
   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
    --------------------------------------- 0.3/12.8 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.8 MB 2.0 MB/s eta 0:00:07
   --- ------------------------------------ 1.0/12.8 MB 2.1 MB/s eta 0:00:06
   ---- ----------------------------------- 1.3/12.8 MB 2.1 MB/s eta 0:00:06
   ----- ---------------------------------- 1.8/12.8 MB 1.9 MB/s eta 0:00:06
   -------- ------------------------------- 2.6/12.8 MB 2.3 MB/s eta 0:00:05
   --------- ------------------------------ 3.1/12.8 MB 2.4 MB/s eta 0:00:04
   ------------ --------------------------- 3.9/12.8 MB 2.5 MB/s eta 0:00:04
   ------------- -------------------------- 4.2/12.8 MB 2.5 MB/s eta 0:00:04
   ------------- -------------------------- 4.5/12.8 MB 2.4 MB/s eta 0:00:04
   --------------- ------------------------ 5.0/12.8 MB 2.3 MB/s eta 0:00:04
   ------------------ --------------------- 5.8/12.8 MB 2.4 MB/s eta 0:00:03
   ------------------- -------------------- 6.3/12.8 MB 2.4 MB/s eta 0:00:03
   --------------------- ------------------ 6.8/12.8 MB 2.4 MB/s eta 0:00:03
   ---------------------- ----------------- 7.3/12.8 MB 2.4 MB/s eta 0:00:03
   ------------------------ --------------- 7.9/12.8 MB 2.4 MB/s eta 0:00:03
   -------------------------- ------------- 8.4/12.8 MB 2.4 MB/s eta 0:00:02
   ---------------------------- ----------- 9.2/12.8 MB 2.5 MB/s eta 0:00:02
   ------------------------------- -------- 10.2/12.8 MB 2.6 MB/s eta 0:00:01
   -------------------------------- ------- 10.5/12.8 MB 2.6 MB/s eta 0:00:01
   --------------------------------- ------ 10.7/12.8 MB 2.5 MB/s eta 0:00:01
   --------------------------------- ------ 10.7/12.8 MB 2.5 MB/s eta 0:00:01
   --------------------------------- ------ 10.7/12.8 MB 2.5 MB/s eta 0:00:01
   -------------------------------------- - 12.3/12.8 MB 2.4 MB/s eta 0:00:01
   ---------------------------------------  12.6/12.8 MB 2.5 MB/s eta 0:00:01
   ---------------------------------------- 12.8/12.8 MB 2.4 MB/s eta 0:00:00
Using cached pytz-2025.2-py2.py3-none-any.whl (509 kB)
Using cached tzdata-2025.2-py2.py3-none-any.whl (347 kB)
Installing collected packages: pytz, tzdata, numpy, pandas

   ---------------------------------------- 0/4 [pytz]
   ---------------------------------------- 0/4 [pytz]
   ---------------------------------------- 0/4 [pytz]
   ---------------------------------------- 0/4 [pytz]
   ---------------------------------------- 0/4 [pytz]
   ---------- ----------------------------- 1/4 [tzdata]
   ---------- ----------------------------- 1/4 [tzdata]
   ---------- ----------------------------- 1/4 [tzdata]
   ---------- ----------------------------- 1/4 [tzdata]
   ---------- ----------------------------- 1/4 [tzdata]
   ---------- ----------------------------- 1/4 [tzdata]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]

In [15]:
pip install SQLAlchemy

Collecting SQLAlchemy
  Using cached sqlalchemy-2.0.41-cp313-cp313-win_amd64.whl.metadata (9.8 kB)
Collecting greenlet>=1 (from SQLAlchemy)
  Using cached greenlet-3.2.3-cp313-cp313-win_amd64.whl.metadata (4.2 kB)
Collecting typing-extensions>=4.6.0 (from SQLAlchemy)
  Using cached typing_extensions-4.14.1-py3-none-any.whl.metadata (3.0 kB)
Using cached sqlalchemy-2.0.41-cp313-cp313-win_amd64.whl (2.1 MB)
Using cached greenlet-3.2.3-cp313-cp313-win_amd64.whl (297 kB)
Using cached typing_extensions-4.14.1-py3-none-any.whl (43 kB)
Installing collected packages: typing-extensions, greenlet, SQLAlchemy

   ------------- -------------------------- 1/3 [greenlet]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   ---------------------------------------- 3/3 [SQLAlchemy]

Successfully installed SQLAlchemy-2.0.41 greenlet-3.2.3 typing-extensions-4.14.1
Note: you may need to restart the kernel to use updated packages.

In [18]:
pip install psycopg2-binary

Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.10-cp313-cp313-win_amd64.whl.metadata (4.8 kB)
Downloading psycopg2_binary-2.9.10-cp313-cp313-win_amd64.whl (2.6 MB)
   ---------------------------------------- 0.0/2.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.6 MB ? eta -:--:--
   -------- ------------------------------- 0.5/2.6 MB 2.1 MB/s eta 0:00:01
   ---------------- ----------------------- 1.0/2.6 MB 2.8 MB/s eta 0:00:01
   -------------------------------- ------- 2.1/2.6 MB 3.2 MB/s eta 0:00:01
   ---------------------------------------- 2.6/2.6 MB 3.2 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.10
Note: you may need to restart the kernel to use updated packages.

In [1]:
from sqlalchemy import create_engine

engine = create_engine("postgresql+psycopg2://sindhulocal:7356@localhost:5432/newphonepay")

with engine.connect() as conn:
    print("✅ Connected using psycopg2!")

✅ Connected using psycopg2!

---aggregated-insurance---

In [2]:
import pandas as pd
import json
import os

In [3]:
agg_ins_statepath=r"C:\Users\admin\Documents\phonepay_project\pulse\data\aggregated\insurance\country\india\state"
agg_ins_statelist=os.listdir(agg_ins_statepath)

In [41]:
agg_ins_data={'state':[],
              'year':[],
              'quarter':[],
              'transaction_type':[],
              'transaction_count':[],
              'transaction_amount':[]}

for state in agg_ins_statelist:
    years=os.listdir(f'{agg_ins_statepath}/{state}')
    for year in years:
        quarter=os.listdir(f'{agg_ins_statepath}/{state}/{year}')
        for qtr in quarter:
            path=(f'{agg_ins_statepath}/{state}/{year}/{qtr}')

            with open(path,'r') as f:
                data=json.load(f)
        
            for i in data['data']['transactionData']:
                transaction_type=i['name']
                count=i['paymentInstruments'][0]['count']
                amount=i['paymentInstruments'][0]['amount']
            #print(district,count,amount)
            #print(district,count,amount,state,year,qtr)
                agg_ins_data['transaction_type'].append(transaction_type)
                agg_ins_data['transaction_count'].append(count)
                agg_ins_data['transaction_amount'].append(amount)
                agg_ins_data['state'].append(state)
                agg_ins_data['year'].append(year)
                agg_ins_data['quarter'].append(int(qtr.strip('.json')))
 
agg_ins_df=pd.DataFrame(agg_ins_data)
agg_ins_df
agg_ins_df.to_sql(name='aggregate_insurance',con=engine,if_exists='append', index=False)

682

---aggregate-transacton----

In [5]:
agg_tr_statepath=r"C:\Users\admin\Documents\phonepay_project\pulse\data\aggregated\transaction\country\india\state"
agg_tr_statelist=os.listdir(agg_tr_statepath)
agg_tr_data={'state':[],
              'year':[],
              'quarter':[],
              'transaction_type':[],
              'transaction_count':[],
              'transaction_amount':[]}

for state in agg_tr_statelist:
    years=os.listdir(f'{agg_tr_statepath}/{state}')
    for year in years:
        quarter=os.listdir(f'{agg_tr_statepath}/{state}/{year}')
        for qtr in quarter :
            path=(f'{agg_tr_statepath}/{state}/{year}/{qtr}')

            with open(path,'r') as f:
                data=json.load(f)
        
            for i in data['data']['transactionData']:
                transaction_type=i['name']
                count=i['paymentInstruments'][0]['count']
                amount=i['paymentInstruments'][0]['amount']
            #print(district,count,amount)
            #print(district,count,amount,state,year,qtr)
                agg_tr_data['transaction_type'].append(transaction_type)
                agg_tr_data['transaction_count'].append(count)
                agg_tr_data['transaction_amount'].append(amount)
                agg_tr_data['state'].append(state)
                agg_tr_data['year'].append(year)
                agg_tr_data['quarter'].append(int(qtr.strip('.json')))
agg_tr_df=pd.DataFrame(agg_tr_data)
agg_tr_df
agg_tr_df.to_sql(name='aggregate_transaction',con=engine,if_exists='append', index=False)

34

----aggregate-user----

In [4]:
agg_user_statepath=r"C:\Users\admin\Documents\phonepay_project\pulse\data\aggregated\user\country\india\state"
agg_user_statelist=os.listdir(agg_user_statepath)
agg_user_data={'state':[],
              'year':[],
              'quarter':[],
              'register_user':[],
              'users_by_device':[],
              'app_opens':[],
              'device_count':[],
              'device_percentage':[]} 

for state in agg_user_statelist:
    years=os.listdir(f'{agg_user_statepath}/{state}')
    for year in years:
        quarter=os.listdir(f'{agg_user_statepath}/{state}/{year}')
        for qtr in quarter :
            path=(f'{agg_user_statepath}/{state}/{year}/{qtr}')
            
            with open(path,'r') as f:
                data=json.load(f)
            try:
                register_user=data['data']['aggregated']['registeredUsers']
                app_open=data['data']['aggregated']['appOpens']
            
               
                for i in data['data']['usersByDevice']:
                    device=i['brand']
                    device_count=i['count']
                    device_percentage=i['percentage']
                    agg_user_data['register_user'].append(register_user)
                    agg_user_data['app_opens'].append(app_open)
                    agg_user_data['users_by_device'].append(device)
                    agg_user_data['device_count'].append(device_count)
                    agg_user_data['device_percentage'].append(device_percentage)
                    agg_user_data['state'].append(state)
                    agg_user_data['year'].append(year)
                    agg_user_data['quarter'].append(int(qtr.strip('.json')))
            except:
                continue  
agg_user_data_df=pd.DataFrame(agg_user_data)  
agg_user_data_df
agg_user_data_df.to_sql(name='aggregate_user',con=engine,if_exists='append', index=False)

732

In [21]:
agg_user_statepath=r"C:\Users\admin\Documents\phonepay_project\pulse\data\aggregated\user\country\india\state"
agg_user_statelist=os.listdir(agg_user_statepath)
agg_user_data1={'state':[],
              'year':[],
              'quarter':[],
              'register_user':[],
              'app_opens':[]}
for state in agg_user_statelist:
    years=os.listdir(f'{agg_user_statepath}/{state}')
    for year in years:
        quarter=os.listdir(f'{agg_user_statepath}/{state}/{year}')
        for qtr in quarter :
            path=(f'{agg_user_statepath}/{state}/{year}/{qtr}')
            
            with open(path,'r') as f:
                data=json.load(f)
                try:
                    register_user = data['data']['aggregated']['registeredUsers']
                    app_open = data['data']['aggregated']['appOpens']
                    
                    agg_user_data1['state'].append(state)
                    agg_user_data1['year'].append(year)
                    agg_user_data1['quarter'].append(int(qtr.strip('.json')))
                    agg_user_data1['register_user'].append(register_user)
                    agg_user_data1['app_opens'].append(app_open)
                except:
                    continue

agg_user_data1_df=pd.DataFrame(agg_user_data1)  
agg_user_data1_df
agg_user_data1_df.to_sql(name='aggregate_user_register',con=engine,if_exists='append', index=False)

8

In [11]:
data['data']['aggregated']

{'registeredUsers': 34750181, 'appOpens': 1994940763}

---map_insurance_hover---

In [62]:
map_insustate_path=r"C:\Users\admin\Documents\phonepay_project\pulse\data\map\insurance\hover\country\india\state"
map_insustate_list=os.listdir(map_insustate_path)
map_ins_data={'state':[],
              'year':[],
              'quarter':[],
              'district':[],
              'transaction_count':[],
              'transaction_amount':[]}

for state in map_insustate_list:
    years=os.listdir(f'{map_insustate_path}/{state}')
    for year in years:
        quarter=os.listdir(f'{map_insustate_path}/{state}/{year}')
        for qtr in quarter :
            path=(f'{map_insustate_path}/{state}/{year}/{qtr}')

            with open(path,'r') as f:
                data=json.load(f)
        
            for i in data['data']['hoverDataList']:
                district=i['name']
                count=i['metric'][0]['count']
                amount=i['metric'][0]['amount']
                #print(district,count,amount)
                #print(district,count,amount,state,year,qtr)
                map_ins_data['district'].append(district)
                map_ins_data['transaction_count'].append(count)
                map_ins_data['transaction_amount'].append(amount)
                map_ins_data['state'].append(state)
                map_ins_data['year'].append(year)
                map_ins_data['quarter'].append(int(qtr.strip('.json')))
 
map_insurance_df=pd.DataFrame(map_ins_data)
map_insurance_df
map_insurance_df.to_sql(name='map_insurance_hover',con=engine,if_exists='append', index=False)

876

--- MAP-Insurance-country---

In [65]:
m_i_c_statepath=r"C:\Users\admin\Documents\phonepay_project\pulse\data\map\insurance\country\india\state"
m_i_c_statelist=os.listdir(m_i_c_statepath)
m_i_c_data={'state':[],
            'year':[],
            'qtr':[],
            'lat':[],
            'lng':[],
            'matric':[],
            'label':[],
            'datalevel':[],
            'gridlevel':[] }

for state in m_i_c_statelist:
    years=os.listdir(f'{m_i_c_statepath}/{state}')
    for year in years:
        quarter=os.listdir(f'{m_i_c_statepath}/{state}/{year}')
        for qtr in quarter:
            m_i_c_path=(f'{m_i_c_statepath}/{state}/{year}/{qtr}')
            
            with open(m_i_c_path, 'r') as f:
                data=json.load(f)
            
           
            datalevel=data['data']['meta']['dataLevel']
            gridLevel=data['data']['meta']['gridLevel']
            

            for i in data['data']['data']['data']:
                m_i_c_data['state'].append(state)
                m_i_c_data['year'].append(year)
                m_i_c_data['qtr'].append(int(qtr.strip('.json')))
                m_i_c_data['lat'].append(i[0])
                m_i_c_data['lng'].append(i[1])
                m_i_c_data['matric'].append(i[2])
                m_i_c_data['label'].append(i[3])
                m_i_c_data['datalevel'].append(datalevel)
                m_i_c_data['gridlevel'].append(gridLevel)

m_i_c_data_df=pd.DataFrame(m_i_c_data)
m_i_c_data_df
m_i_c_data_df.to_sql(name='map_insurance_country',con=engine,if_exists='append', index=False)

137

---MAP -transaction

In [78]:
map_state_path=r"C:\Users\admin\Documents\phonepay_project\pulse\data\map\transaction\hover\country\india\state"
map_state_list=os.listdir(map_state_path)
map_trans_data={'state':[],'year':[],'quarter':[],'district':[],'transacion_count':[],'transaction_amount':[]}

for state in map_state_list:
   years=os.listdir(f'{map_state_path}/{state}')
   for year in years:
      quarter=os.listdir(f'{map_state_path}/{state}/{year}')
      for qtr in quarter:
         path=f'{map_state_path}/{state}/{year}/{qtr}'
         #print(path)

         with open(path,'r') as f:
            data=json.load(f)
        
         for i in data['data']['hoverDataList']: 
            district=i['name']
            count=i['metric'][0 ]['count']
            amount=i['metric'][0]['amount']
               #print(district,count,amount,state,year,qtr)
            map_trans_data['district'].append(district)
            map_trans_data['transacion_count'].append(count)
            map_trans_data['transaction_amount'].append(amount)
            map_trans_data['state'].append(state)
            map_trans_data['year'].append(year)
            map_trans_data['quarter'].append(int(qtr.strip('.json')))
map_transaction_df=pd.DataFrame(map_trans_data)
map_transaction_df
map_transaction_df.to_sql(name='map_transaction',con=engine,if_exists='append', index=False)

604

---map_user--

In [69]:
m_u_statepath=r"C:\Users\admin\Documents\phonepay_project\pulse\data\map\user\hover\country\india\state"
m_u_statelist=os.listdir(m_u_statepath)
map_user_data={'state':[],
              'year':[],
              'quarter':[],
              'district':[],
              'count':[],
              'appopen':[]}

for state in m_u_statelist:
    years=os.listdir(f'{m_u_statepath}/{state}')
    for year in years:
        quarter=os.listdir(f'{m_u_statepath}/{state}/{year}')
        for qtr in quarter :
            path=(f'{m_u_statepath}/{state}/{year}/{qtr}')

            with open(path,'r') as f:
                data=json.load(f)
        
            for i,j in data['data']['hoverData'].items():
                district3=i
                reg_user=j['registeredUsers']
                app_count=j['appOpens']
            #print(district,count,amount)
            #print(district,count,amount,state,year,qtr)
                map_user_data['district'].append(district3)
                map_user_data['count'].append(reg_user)
                map_user_data['appopen'].append(app_count)
                map_user_data['state'].append(state)
                map_user_data['year'].append(year)
                map_user_data['quarter'].append(int(qtr.strip('.json')))
map_user_df=pd.DataFrame(map_user_data)
map_user_df
map_user_df.to_sql(name='map_user',con=engine,if_exists='append', index=False)

608

---Top-insurance----

In [8]:
top_ins_statepath=r"C:\Users\admin\Documents\phonepay_project\pulse\data\top\insurance\country\india\state"
top_ins_statelist=os.listdir(top_ins_statepath)
top_ins_dis_data={
                'state':[],
                'year':[],
                'quarter':[],
                'dis_name':[],
                'transaction_count':[],
                'transaction_amount':[]}
                
for state in top_ins_statelist:
    years=os.listdir(f'{top_ins_statepath}/{state}')
    for year in years:
        quarter=os.listdir(f'{top_ins_statepath}/{state}/{year}')
        for qtr in quarter:
            path=f'{top_ins_statepath}/{state}/{year}/{qtr}'
                
            with open(path, 'r') as f:
                data=json.load(f)
                try:
                    for i in data['data']['districts']:
                        state_en=i['entityName']
                        count=i['metric']['count']
                        amount=i['metric']['amount']
                        top_ins_dis_data['dis_name'].append(state_en)
                        top_ins_dis_data['transaction_count'].append(count)
                        top_ins_dis_data['transaction_amount'].append(amount)
                        top_ins_dis_data['state'].append(state)
                        top_ins_dis_data['year'].append(year)
                        top_ins_dis_data['quarter'].append(int(qtr.strip('.json')))
                except:
                    continue     

top_ins_dis_data_df=pd.DataFrame(top_ins_dis_data)
top_ins_dis_data_df   
top_ins_dis_data_df.to_sql(name='top_insurance_district',con=engine,if_exists='append', index=False)

608

In [89]:
top_ins_pin_data={
                'state':[],
                'year':[],
                'quarter':[],
                'entity_name':[],
                'transaction_count':[],
                'transaction_amount':[]}
                
for state in top_ins_statelist:
    years=os.listdir(f'{top_ins_statepath}/{state}')
    for year in years:
        quarter=os.listdir(f'{top_ins_statepath}/{state}/{year}')
        for qtr in quarter:
            path=f'{top_ins_statepath}/{state}/{year}/{qtr}'
                
            with open(path, 'r') as f:
                data=json.load(f)
                try:
                    for i in data['data']['pincodes']:
                        state_en=i['entityName']
                        count=i['metric']['count']
                        amount=i['metric']['amount']
                        top_ins_pin_data['entity_name'].append(state_en)
                        top_ins_pin_data['transaction_count'].append(count)
                        top_ins_pin_data['transaction_amount'].append(amount)
                        top_ins_pin_data['state'].append(state)
                        top_ins_pin_data['year'].append(year)
                        top_ins_pin_data['quarter'].append(int(qtr.strip('.json')))
                except:
                    continue                                       
              

top_ins_pin_data_df=pd.DataFrame(top_ins_pin_data)
top_ins_pin_data_df
                         
top_ins_pin_data_df.to_sql(name='top_insurance_pincode',con=engine,if_exists='append', index=False)

668

----top-transaction------

In [92]:
top_trans_statepath=r'C:\Users\admin\Documents\phonepay_project\pulse\data\top\transaction\country\india\state' 
top_trans_statelist=os.listdir(top_trans_statepath)
top_trans_dis_data={'state':[],
                    'year':[],
                    'quarter':[],
                    'entity_name':[],
                    'transaction_count':[],
                    'transaction_amount':[]
                    }
for state in top_trans_statelist:
    years=os.listdir(f'{top_trans_statepath}/{state}')
    for year in years:
        quarter=os.listdir(f'{top_trans_statepath}/{state}/{year}') 
        for qtr in quarter:
            top_trans_path=(f'{top_trans_statepath}/{state}/{year}/{qtr}') 

            with open(top_trans_path, 'r') as f:
                data=json.load(f)

            for i in data['data']['districts']:
                en_name=i['entityName']
                count=i['metric']['count']
                amount=i['metric']['amount']
                top_trans_dis_data['entity_name'].append(en_name)
                top_trans_dis_data['transaction_count'].append(count)
                top_trans_dis_data['transaction_amount'].append(amount)
                top_trans_dis_data['state'].append(state)
                top_trans_dis_data['year'].append(year)
                top_trans_dis_data['quarter'].append(int(qtr.strip('.json')))

top_trans_dis_data_df=pd.DataFrame(top_trans_dis_data)
top_trans_dis_data_df
top_trans_dis_data_df.to_sql(name='top_transaction_district',con=engine,if_exists='append', index=False)

296

In [94]:
top_trans_pin_data={'state':[],
                    'year':[],
                    'quarter':[],
                    'entity_name':[],
                    'transaction_count':[],
                    'transaction_amount':[]
                    }
for state in top_trans_statelist:
    years=os.listdir(f'{top_trans_statepath}/{state}')
    for year in years:
        quarter=os.listdir(f'{top_trans_statepath}/{state}/{year}') 
        for qtr in quarter:
            top_trans_path=(f'{top_trans_statepath}/{state}/{year}/{qtr}') 

            with open(top_trans_path, 'r') as f:
                data=json.load(f)

            for i in data['data']['pincodes']:
                en_name=i['entityName']
                count=i['metric']['count']
                amount=i['metric']['amount']
                top_trans_pin_data['entity_name'].append(en_name)
                top_trans_pin_data['transaction_count'].append(count)
                top_trans_pin_data['transaction_amount'].append(amount)
                top_trans_pin_data['state'].append(state)
                top_trans_pin_data['year'].append(year)
                top_trans_pin_data['quarter'].append(int(qtr.strip('.json')))

top_trans_pin_data_df=pd.DataFrame(top_trans_pin_data)
top_trans_pin_data_df
top_trans_pin_data_df.to_sql(name='top_transaction_pincode',con=engine,if_exists='append', index=False)

999

----top-user-----

In [6]:
top_user_state_path=r"C:\Users\admin\Documents\phonepay_project\pulse\data\top\user\country\india\state"
top_user_state_list=os.listdir(top_user_state_path)
top_user_dis_data={'state':[],
                    'year':[],
                    'qtr':[],
                    'dis_name':[],
                    'reg_user':[]
                    }
for state in top_user_state_list:
    years=os.listdir(f'{top_user_state_path}/{state}')
    for year in years:
        quarter=os.listdir(f'{top_user_state_path}/{state}/{year}') 
        for qtr in quarter:
            top_trans_path=(f'{top_user_state_path}/{state}/{year}/{qtr}') 

            with open(top_trans_path, 'r') as f:
                data=json.load(f)

            for i in data['data']['districts']:
                name=i['name']
                reg_user=i['registeredUsers']
                top_user_dis_data['dis_name'].append(name)
                top_user_dis_data['reg_user'].append(reg_user)
                top_user_dis_data['state'].append(state)
                top_user_dis_data['year'].append(year)
                top_user_dis_data['qtr'].append(int(qtr.strip('.json')))

top_user_dis_data_df=pd.DataFrame(top_user_dis_data)
top_user_dis_data_df
top_user_dis_data_df.to_sql(name='top_user_dis_data',con=engine,if_exists='append', index=False)

296

In [7]:
top_user_pin_data={'state':[],
                    'year':[],
                    'quarter':[],
                    'entity_name':[],
                    'reg_user':[]
                    }
for state in top_user_state_list:
    years=os.listdir(f'{top_user_state_path}/{state}')
    for year in years:
        quarter=os.listdir(f'{top_user_state_path}/{state}/{year}') 
        for qtr in quarter:
            top_trans_path=(f'{top_user_state_path}/{state}/{year}/{qtr}') 

            with open(top_trans_path, 'r') as f:
                data=json.load(f)

            for i in data['data']['pincodes']:
                name=i['name']
                reg_user=i['registeredUsers']
                top_user_pin_data['entity_name'].append(name)
                top_user_pin_data['reg_user'].append(reg_user)
                top_user_pin_data['state'].append(state)
                top_user_pin_data['year'].append(year)
                top_user_pin_data['quarter'].append(int(qtr.strip('.json')))

top_user_pin_data_df=pd.DataFrame(top_user_pin_data)
top_user_pin_data_df
top_user_pin_data_df.to_sql(name='top_user_pin_data',con=engine,if_exists='append', index=False)
top_user_pin_data_df

                          state  year  quarter entity_name  reg_user
0     andaman-&-nicobar-islands  2018        1      744103      1608
1     andaman-&-nicobar-islands  2018        1      744101      1108
2     andaman-&-nicobar-islands  2018        1      744105      1075
3     andaman-&-nicobar-islands  2018        1      744102      1006
4     andaman-&-nicobar-islands  2018        1      744104       272
...                         ...   ...      ...         ...       ...
9995                west-bengal  2024        4      733134    169596
9996                west-bengal  2024        4      700059    169448
9997                west-bengal  2024        4      711302    146034
9998                west-bengal  2024        4      700150    142151
9999                west-bengal  2024        4      711106    142077

[10000 rows x 5 columns]

In [8]:
from geopy.geocoders import Nominatim

In [9]:
geolocator = Nominatim(user_agent="State_map")
location = geolocator.geocode("andaman-&-nicobar-islands")
location

Location(Nicobar Islands, Great Nicobar, Nicobar, Andaman and Nicobar Islands, India, (7.0000167, 93.8110528, 0.0))

In [10]:
import time

In [12]:
state_lat_lon={'state':[],'lat':[],'lon':[]}
for i in top_user_pin_data_df['state'].unique():
    location = geolocator.geocode(i)
    lat=location.latitude
    lon=location.longitude
    state_lat_lon['state'].append(i)
    state_lat_lon['lat'].append(lat)
    state_lat_lon['lon'].append(lon)
    print(i,lat,lon)
    time.sleep(1)

andaman-&-nicobar-islands 7.0000167 93.8110528
andhra-pradesh 15.9240905 80.1863809
arunachal-pradesh 28.0937702 94.5921326
assam 26.4073841 93.2551303
bihar 25.6440845 85.906508
chandigarh 30.7334421 76.7797143
chhattisgarh 21.6637359 81.8406351
dadra-&-nagar-haveli-&-daman-&-diu 20.7137783 70.9853635
delhi 28.6328027 77.2197713
goa 15.3004543 74.0855134
gujarat 22.3850051 71.745261
haryana 29.0 76.0
himachal-pradesh 31.9292352 77.1828462
jammu-&-kashmir 33.6649297 75.1629584
jharkhand 23.4559809 85.2557301
karnataka 14.5203896 75.7223521
kerala 10.3528744 76.5120396
ladakh 33.9456407 77.6568576
lakshadweep 10.3337313 72.9205386
madhya-pradesh 23.8143419 77.5340719
maharashtra 18.9068356 75.6741579
manipur 24.7208818 93.9229386
meghalaya 25.5379432 91.2999102
mizoram 23.2146169 92.8687612
nagaland 26.1630556 94.5884911
odisha 20.5431241 84.6897321
puducherry 10.9156489 79.8069488
punjab 30.9293211 75.5004841
rajasthan 26.8105777 73.7684549
sikkim 27.601029 88.4541364
tamil-nadu 10.9094334 78.3665347
telangana 17.8495919 79.1151663
tripura 23.7750823 91.7025091
uttar-pradesh 27.1303344 80.859666
uttarakhand 30.0417376 79.089691
west-bengal 22.9964948 87.6855882

In [2]:
import pandas as pd

In [13]:
state_df=pd.DataFrame(state_lat_lon)
state_df

                                 state        lat        lon
0            andaman-&-nicobar-islands   7.000017  93.811053
1                       andhra-pradesh  15.924091  80.186381
2                    arunachal-pradesh  28.093770  94.592133
3                                assam  26.407384  93.255130
4                                bihar  25.644085  85.906508
5                           chandigarh  30.733442  76.779714
6                         chhattisgarh  21.663736  81.840635
7   dadra-&-nagar-haveli-&-daman-&-diu  20.713778  70.985364
8                                delhi  28.632803  77.219771
9                                  goa  15.300454  74.085513
10                             gujarat  22.385005  71.745261
11                             haryana  29.000000  76.000000
12                    himachal-pradesh  31.929235  77.182846
13                     jammu-&-kashmir  33.664930  75.162958
14                           jharkhand  23.455981  85.255730
15                           karnataka  14.520390  75.722352
16                              kerala  10.352874  76.512040
17                              ladakh  33.945641  77.656858
18                         lakshadweep  10.333731  72.920539
19                      madhya-pradesh  23.814342  77.534072
20                         maharashtra  18.906836  75.674158
21                             manipur  24.720882  93.922939
22                           meghalaya  25.537943  91.299910
23                             mizoram  23.214617  92.868761
24                            nagaland  26.163056  94.588491
25                              odisha  20.543124  84.689732
26                          puducherry  10.915649  79.806949
27                              punjab  30.929321  75.500484
28                           rajasthan  26.810578  73.768455
29                              sikkim  27.601029  88.454136
30                          tamil-nadu  10.909433  78.366535
31                           telangana  17.849592  79.115166
32                             tripura  23.775082  91.702509
33                       uttar-pradesh  27.130334  80.859666
34                         uttarakhand  30.041738  79.089691
35                         west-bengal  22.996495  87.685588

In [22]:
pd.merge(agg_tr_df,state_df,on='state')

,state,year,quarter,transaction_type,transaction_count,transaction_amount,lat,lon
0,andaman-&-nicobar-islands,2018,1,Recharge & bill payments,4200,1.845307e+06,7.000017,93.811053
1,andaman-&-nicobar-islands,2018,1,Peer-to-peer payments,1871,1.213866e+07,7.000017,93.811053
2,andaman-&-nicobar-islands,2018,1,Merchant payments,298,4.525072e+05,7.000017,93.811053
3,andaman-&-nicobar-islands,2018,1,Financial Services,33,1.060142e+04,7.000017,93.811053
4,andaman-&-nicobar-islands,2018,1,Others,256,1.846899e+05,7.000017,93.811053
...,...,...,...,...,...,...,...,...
5029,west-bengal,2024,4,Merchant payments,655100809,3.892862e+11,22.996495,87.685588
5030,west-bengal,2024,4,Peer-to-peer payments,493217788,1.361927e+12,22.996495,87.685588
5031,west-bengal,2024,4,Recharge & bill payments,76043195,5.753406e+10,22.996495,87.685588
5032,west-bengal,2024,4,Financial Services,2352084,8.472965e+08,22.996495,87.685588
5033,west-bengal,2024,4,Others,421806,5.053641e+08,22.996495,87.685588

In [14]:
state_df = pd.DataFrame(state_lat_lon)
state_df.to_csv("state_lat_lon.csv", index=False)